### PR TITLE
Update InstallServer.wiki

### PR DESCRIPTION
**Pull request by Softcopy**

### CODE REVIEW

**Comment by Softcopy** [comment]
Updated InstallServer.wiki

**Comment by Softcopy** [comment]
Updated InstallServer.wiki

**Comment by GoogleCodeExporter** [comment]
Original comment by `ibe...@gmail.com` on 13 Oct 2011 at 3:45
- Added labels: **Target-ServerDLL**

**Comment by GoogleCodeExporter** [comment]
```
Also need to add cvars for asw_carnage_max and asw_carnage_interval_min.

Description:
asw_carnage_max: Limits the maximum number of aliens a spawner can put out; 
won't affect unlimited spawners.

asw_carnage_interval_min: Limits how fast a spawner can put out aliens.
```

Original comment by `ibe...@gmail.com` on 13 Oct 2011 at 3:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `ibe...@gmail.com` on 20 Oct 2011 at 6:44
- Changed state: **Done**

**Pull request closed without merging**
